services:
  nginx:
    image: "nginx:latest"             # Use the latest Nginx image
    container_name: "sq_nginx"        # Give the container a name
    restart: always                  # Restart the container if it crashes
    ports:
      - "80:80"                      # Map port 80 on the host to port 80 in the container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Mount your Nginx configuration file
      
  api:
    container_name: sq_api           # Name for the API container
    image: ghcr.io/tdjsnelling/sqtracker-api:latest  # Use the latest API image
    ports:
      - "3001:3001"                  # Map port 3001
    volumes:
      - type: bind                 # Use a bind mount for the configuration file
        source: ./config.js         # Path to your config.js file on the host
        target: /sqtracker/config.js # Path to the config file within the container
        
  client:
    container_name: sq_client        # Name for the client container
    image: ghcr.io/tdjsnelling/sqtracker-client:latest # Use the latest client image
    ports:
      - "3000:3000"                  # Map port 3000
    volumes:
      - type: bind                 # Use a bind mount for the configuration file
        source: ./config.js         # Path to your config.js file on the host
        target: /sqtracker/config.js # Path to the config file within the container
    # - ./favicon.png:/sqtracker/public/favicon.png  # Optional: Mount favicon (uncomment if needed)
    # - ./favicon.ico:/sqtracker/public/favicon.ico  # Optional: Mount favicon (uncomment if needed)
    depends_on:                     # Ensure the client starts *after* the API
      - api
