services:
  nginx:
    image: "nginx:latest"            
    container_name: "sq_nginx"        # Give the container a name
    restart: always                  # Restart the container if it crashes
    ports:
      - "80:80"                      # Map port 80 on the host to port 80 in the container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
      
  api:
    container_name: sq_api           # Name for the API container
    image: ghcr.io/tdjsnelling/sqtracker-api:latest 
    ports:
      - "3001:3001"                 
    volumes:
      - type: bind                 
        source: ./config.js        
        target: /sqtracker/config.js 
        
  client:
    container_name: sq_client        # Name for the client container
    image: ghcr.io/tdjsnelling/sqtracker-client:latest
    ports:
      - "3000:3000"                 
    volumes:
      - type: bind                 
        source: ./config.js         
        target: /sqtracker/config.js 
      # - ./favicon.png:/sqtracker/client/public/favicon.png  # Optional: Mount favicon (uncomment if needed)
      # - ./favicon.ico:/sqtracker/client/public/favicon.ico  # Optional: Mount favicon (uncomment if needed)
    depends_on:                     # Ensure the client starts *after* the API
      - api
