services:
  nginx:
    image: "nginx:latest"            
    container_name: "nexus_nginx"
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
      
  api:
    image: effxct290/nexustracker-api:latest-amd64
    container_name: nexus_api
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - type: bind
        source: ./config.js
        target: /nexustracker/config.js
    labels:
      - "com.nexustracker.description=NexusTracker API Service"
      - "com.nexustracker.maintainer=EFFXCT290"
        
  client:
    image: effxct290/nexustracker-client:latest-amd64
    container_name: nexus_client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./config.js
        target: /nexustracker/config.js
    labels:
      - "com.nexustracker.description=NexusTracker Web Client"
      - "com.nexustracker.maintainer=EFFXCT290"
    depends_on:
      - api
