services:
  npm:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    restart: unless-stopped
    ports:
      - '80:80'    # HTTP
      - '443:443'  # HTTPS
      - '81:81'    # Admin UI
    volumes:
      - ./npm-data:/data
      - ./npm-letsencrypt:/etc/letsencrypt
    networks:
      - tracker-network
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
      DISABLE_IPV6: "true"

      
  api:
    image: effxct290/nexustracker-api:latest-amd64
    container_name: nexus_api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./config.js
        target: /nexustracker/config.js
    labels:
      - "com.nexustracker.description=NexusTracker API Service"
      - "com.nexustracker.maintainer=EFFXCT290"
    networks:
      - tracker-network
    expose:
      - "3001"
    environment:
      - SQ_BASE_URL=${SQ_BASE_URL:-http://your-server-ip} # change http to https if you want https
      - SQ_API_URL=${SQ_API_URL:-http://your-server-ip/api} # change http to https if you want https
    logging: # Disable Block to enable Logs
      driver: "none"
        
  client:
    image: effxct290/nexustracker-client:latest-amd64
    container_name: nexus_client
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./config.js
        target: /nexustracker/config.js
    labels:
      - "com.nexustracker.description=NexusTracker Web Client"
      - "com.nexustracker.maintainer=EFFXCT290"
    depends_on:
      - api
    networks:
      - tracker-network
    expose:
      - "3000"
    environment:
      - SQ_BASE_URL=${SQ_BASE_URL:-http://your-server-ip} # change http to https if you want https
      - SQ_API_URL=${SQ_API_URL:-http://your-server-ip/api} # change http to https if you want https
    logging: # Disable Block to enable Logs
      driver: "none"

networks:
  tracker-network:
    driver: bridge
